# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "win10"
  config.vm.hostname = "node3"
  config.vm.network "public_network", ip: "192.168.101.85", netmask: "255.255.255.0", gateway: "192.168.101.254", bridge: "enp2s0"
  config.vm.provider "virtualbox" do |vb|
    #vb.gui = true
    vb.cpus = 2
    vb.memory = "2048"
  end
  config.vm.provision "shell", run: "always", inline: <<-SHELL
    netsh advfirewall set allprofiles state off
    ROUTE ADD 0.0.0.0  MASK 0.0.0.0  192.168.101.254  METRIC 25
  SHELL
end

