# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.network :public_network, ip: "192.168.101.85", netmask: "255.255.255.0", bridge: "enp2s0", docker_network__gateway: "192.168.101.254"
  config.vm.provider "docker" do |d|
    d.image = "dave/docker"
    #d.build_dir = "."
    d.create_args = ["--hostname=docker", "-v", "/data/var-lib-docker:/var/lib/docker"]
    d.privileged = true
    d.cmd = ["/sbin/init"]
  end

end
